#!/bin/bash
files=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep '\.jsx\?$')

# Prevent ESLint help message if no files matched
if [[ $files = "" ]] ; then
  exit 0
fi

failed=0
for file in ${files}; do
  git show :$file | eslint --stdin --stdin-filename $file --rulesdir scripts/eslint-rules/ --rule '{"no-invalid-log-calls":[2]}'
  if [[ $? != 0 ]] ; then
    failed=1
  fi
done;

if [[ $failed != 0 ]] ; then
  echo "ESLint exited with non-zero status -- commit denied"
  echo "Tip: If you have fixed the issue and are still getting"
  echo "Tip: errors, do not forget to stage the changes"
  exit $failed
fi
